FORMAT: 1A
HOST: https://api.myperfit.com/v2

# Perfit API v2

Acá va la intro.

## Group Autenticación

### Login [POST /login]
Existen 3 formas de autenticación:
1. Indicando `user` + `password`. Siendo `user` usuario@cuenta o la dirección de email del usuario.
2. Indicando `user` + `password` + [`account`] . Siendo `user` el email del usuario. Opcionalmente indicar la cuenta en caso de email duplicado. Ver documentación, sección autenticación.
3. Indicando únicamente `apikey`.

Para los casos 1 y 2 puede indicarse también `newPassword` en el caso que sea necesaria un actualización de la contraseña.

+ Request (application/json)

    + Attributes
      + user: diego@perfit.com.ar (string, optional) - email o username@account
      + password: 123 (string, optional)
      + account (string, optional)
      + apikey (string, optional)
      + newPassword (string, optional)

+ Response 201 (application/json)

    Sesión iniciada con éxito.
    
    + Body
    
            {
                "url": "/login",
                "success" : true,
                "data": {
                    "token": "Shjg23Asd4Sdg8fd23F4eg8rF83kgd2s",
                    "tokenExpiration": 3600,
                    "user": "diego",
                    "account": "perfit",
                    "acl": {
                      "perfit": [
                          "lists:list",
                          "contacts:list",
                          "contacts:create",
                          "contacts:delete",
                          "contacts:update"
                      ]
                    }
                }
            }

+ Response 401 (application/json)

    El usuario no existe o la contraseña es inválida. 
    
    + Body
    
            {
                "url": "/login",
                "success" : false,
                  "error": {
                    "status": 401,
                    "type": "UNAUTHORIZED",
                    "userMessage": "The user is not authorized to login"
                  }
            }

+ Response 409 (application/json)

    Si existe más de un usuario asociados al `email` indicado, se dede incluir `account` en el request. Se indica en `data` el array de cuentas a las cuales se tiene acceso.
    
    + Body
    
            {
                "href": "/login",
                "success": false,
                "error": { 
                    "status": 409,
                    "type": "ACCOUNT_REQUIRED",
                    "userMessage": "Se debe indicar la cuenta donde iniciar sesión"
                },
                "data": ["cuenta1", "cuenta2", "cuenta3", ...]
            }

### Logout [POST /logout]
Invalida el token indicado en el header `X-Auth-Token` o en el querystring `token`.

+ Request

    + Headers
    
            X-Auth-Token: access_token

+ Response 200 (application/json)

        {
            "url": "/logout",
            "success" : true
        }


# Group Listas

## Lists Collection [/{account}/lists{?q,offset,limit,sortby,sortdir}]

### Listado y búsqueda [GET]

+ Parameters
  + account: testaccount (string, required) - Nombre de la cuenta
  + offset: 0 (number, optional) - Inicio de paginado
  + limit: 10 (number, optional) - Cantidad de resultados
  + q (optional) - Búsqueda por `name`
  + sortby: name (enum[string], optional) - Tipo de ordenamiento
        + Members
            + `name`
            + `created`
            + `lastMailed`
  + sortdir: asc (enum[string], optional) - Sentido de ordenamiento
        + Members
            + `asc`
            + `desc`
  
+ Response 200 (application/json)

        {
            "url": "/testaccount/lists",
            "success" : true,
            "sort": {
                "sortby": "name",
                "sortdir": "asc"
            },
            "paging": {
                "offset": 0,
                "limit": 10,
                "results": 2,
                "total": 2
            },
            "data": [
                {
                    "id": 1,
                    "name": "Suscriptos a Newsletter",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }, 
                {
                    "id": 2,
                    "name": "Suscriptos a Ofertas",
                    "description": "Listado de contactos suscriptos a las ofertas",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 221,
                    "totalContacts": 204,
                    "quality": 0.34,
                    "tags": [ ]
                }
            ]
        }

### Crear una nueva lista [POST]

+ Parameters

    + account: testaccount (string, required) - Nombre de la cuenta



+ Request (application/x-www-form-urlencoded)

    + Attributes
        + name: Nueva lista (string) - Foo param
    
    + Headers

            X-Auth-Token: access_token
            
+ Response 201 (application/json)

    + Headers

            Location: /testaccount/lists/1
        
    + Body
    
            {
                "url": "/testaccount/lists",
                "success" : true,
                "data": {
                    "id": 1,
                    "name": "Nueva lista",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }
            }


## List item [/{account}/lists/{id}]

+ Parameters
    + account: testaccount (string, required)
    + id: 1 (number, required)
    
### Obtener una lista [GET]

+ Response 200 (application/json)

        {
            "url": "/testaccount/lists/1",
            "success" : true,
            "data": {
                "id": 1,
                "name": "Suscriptos a Newsletter",
                "description": "Listado de contactos suscriptos al news",
                "created": "2014-05-17 05:30:00+0000",
                "lastMailed": "2014-05-18 05:30:00+0000",
                "activeContacts": 120,
                "totalContacts": 100,
                "quality": 0.23,
                "tags": [ ]
            }
        }



### Modificar una lista [PUT]

+ Request (application/json)

        {
            "description": "Nueva descrpción de la lista"
        }

+ Response 200  (application/json)

        {
            "url": "/testaccount/lists/1",
            "success" : true,
            "data": {
                "description": "Nueva descrpción de la lista"
            } 
        }

### Eliminar una lista [DELETE]

+ Response 201  (application/json)

        {
            "url": "/testaccount/lists",
            "success" : true
        }

# Group Campañas

## Campaigns List [/{account}/campaigns{?q,offset,limit,sortby,sortdir}]

### Listar todas las campañas [GET]

+ Parameters
  + account: testaccount (string, required) - Nombre de la cuenta
  + offset: 0 (number, optional) - Inicio de paginado
  + limit: 10 (number, optional) - Cantidad de resultados
  + q (optional) - Búsqueda por `name`
  + sortby: name (enum[string], optional) - Tipo de ordenamiento
        + Members
            + `name`
            + `created`
            + `lastMailed`
  + sortdir: asc (enum[string], optional) - Sentido de ordenamiento
        + Members
            + `asc`
            + `desc`

+ Response 200 (application/json)

        {
            "url": "/testaccount/campaigns",
            "success" : true,
            "sort": {
                "sortby": "name",
                "sortdir": "asc"
            },
            "paging": {
                "offset": 0,
                "limit": 10,
                "results": 2,
                "total": 2
            },
            "data": [
                {
                    "id": 1,
                    "name": "Suscriptos a Newsletter",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }
            ]
        }