FORMAT: 1A
HOST: https://api.myperfit.com/v2

# Perfit API

## Group Autenticación

### Login [POST /login]
Existen 3 formas de autenticación:
1. Indicando `user` + `password`. Siendo `user` usuario@cuenta o la dirección de email del usuario.
2. Indicando `user` + `password` + [`account`] . Siendo `user` el email del usuario. Opcionalmente indicar la cuenta en caso de email duplicado. Ver documentación, sección autenticación.
3. Indicando únicamente `apikey`.

Para los casos 1 y 2 puede indicarse también `newPassword` en el caso que sea necesaria un actualización de la contraseña.

+ Request (application/json)

    + Attributes
      + user: diego@perfit.com.ar (string, optional) - email o username@account
      + password: 123 (string, optional)
      + account (string, optional)
      + apikey (string, optional)
      + newPassword (string, optional)

+ Response 201 (application/json)

    Sesión iniciada con éxito.
    
    + Body
    
            {
                "url": "/login",
                "success" : true,
                "data": {
                    "token": "Shjg23Asd4Sdg8fd23F4eg8rF83kgd2s",
                    "tokenExpiration": 3600,
                    "user": "diego",
                    "account": "perfit",
                    "acl": {
                      "perfit": [
                          "lists:list",
                          "contacts:list",
                          "contacts:create",
                          "contacts:delete",
                          "contacts:update"
                      ]
                    }
                }
            }

+ Response 401 (application/json)

    El usuario no existe o la contraseña es inválida. 
    
    + Body
    
            {
                "url": "/login",
                "success" : false,
                  "error": {
                    "status": 401,
                    "type": "UNAUTHORIZED",
                    "userMessage": "The user is not authorized to login"
                  }
            }

+ Response 409 (application/json)

    Si existe más de un usuario asociados al `email` indicado, se dede incluir `account` en el request. Se indica en `data` el array de cuentas a las cuales se tiene acceso.
    
    + Body
    
            {
                "href": "/login",
                "success": false,
                "error": { 
                    "status": 409,
                    "type": "ACCOUNT_REQUIRED",
                    "userMessage": "Se debe indicar la cuenta donde iniciar sesión"
                },
                "data": ["cuenta1", "cuenta2", "cuenta3", ...]
            }

### Logout [POST /logout]
Invalida el token indicado en el header `X-Auth-Token` o en el querystring `token`.

+ Request

    + Headers
    
            X-Auth-Token: access_token

+ Response 200 (application/json)

        {
            "url": "/logout",
            "success" : true
        }



# Group Listas

## Colección [/{account}/lists{?q,offset,limit,sortby,sortdir}]

### Listado y búsqueda [GET]

+ Parameters
  + account: testaccount (string, required) - Nombre de la cuenta
  + offset: 0 (number, optional) - Inicio de paginado
  + limit: 10 (number, optional) - Cantidad de resultados
  + q (optional) - Búsqueda por `name`
  + sortby: name (enum[string], optional) - Tipo de ordenamiento
        + Members
            + `name`
            + `created`
            + `lastMailed`
  + sortdir: asc (enum[string], optional) - Sentido de ordenamiento
        + Members
            + `asc`
            + `desc`
  
+ Response 200 (application/json)

        {
            "url": "/testaccount/lists",
            "success" : true,
            "sort": {
                "sortby": "name",
                "sortdir": "asc"
            },
            "paging": {
                "offset": 0,
                "limit": 10,
                "results": 2,
                "total": 2
            },
            "data": [
                {
                    "id": 1,
                    "name": "Suscriptos a Newsletter",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }, 
                {
                    "id": 2,
                    "name": "Suscriptos a Ofertas",
                    "description": "Listado de contactos suscriptos a las ofertas",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 221,
                    "totalContacts": 204,
                    "quality": 0.34,
                    "tags": [ ]
                }
            ]
        }

### Crear nueva lista [POST]

+ Parameters

    + account: testaccount (string, required) - Nombre de la cuenta



+ Request (application/x-www-form-urlencoded)

    + Attributes
        + name: Nueva lista (string) - Foo param
    
    + Headers

            X-Auth-Token: access_token
            
+ Response 201 (application/json)

    + Headers

            Location: /testaccount/lists/1
        
    + Body
    
            {
                "url": "/testaccount/lists",
                "success" : true,
                "data": {
                    "id": 1,
                    "name": "Nueva lista",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }
            }

## Elemento [/{account}/lists/{id}]

+ Parameters
    + account: testaccount (string, required)
    + id: 1 (number, required)

### Obtener lista [GET]

+ Response 200 (application/json)

        {
            "url": "/testaccount/lists/1",
            "success" : true,
            "data": {
                "id": 1,
                "name": "Suscriptos a Newsletter",
                "description": "Listado de contactos suscriptos al news",
                "created": "2014-05-17 05:30:00+0000",
                "lastMailed": "2014-05-18 05:30:00+0000",
                "activeContacts": 120,
                "totalContacts": 100,
                "quality": 0.23,
                "tags": [ ]
            }
        }

### Modificar lista [PUT]

+ Request (application/json)

        {
            "description": "Nueva descrpción de la lista"
        }

+ Response 200  (application/json)

        {
            "url": "/testaccount/lists/1",
            "success" : true,
            "data": {
                "description": "Nueva descrpción de la lista"
            } 
        }

### Eliminar lista [DELETE]

+ Response 201  (application/json)

        {
            "url": "/testaccount/lists",
            "success" : true
        }



# Group Contactos

## Colección [/{account}/contacts{?q,offset,limit,sortby,sortdir}]

### Listado y búsqueda [GET]

+ Parameters
  + account: testaccount (string, required) - Nombre de la cuenta
  + offset: 0 (number, optional) - Inicio de paginado
  + limit: 20 (number, optional) - Cantidad de resultados
  + q (optional) - Búsqueda por `email`
  + state (optional) - Estado de los contactos
        + Members
            + `active`
            + `unsubscribed`
            + `compained`
            + `bounced`
            + `inactive`
  + domain (optional) - Dominio de los contactos.
  + interest (optional) - Se pasa el ID.
  + list (optional) - Se pasa el ID.
  + sortby: email (enum[string], optional) - Tipo de ordenamiento
        + Members
            + `email`
            + `quality`
  + sortdir: asc (enum[string], optional) - Sentido de ordenamiento
        + Members
            + `asc`
            + `desc`

+ Response 200 (application/json)

        {
  "href": "/v2/testaccount/contacts",
  "success": true,
  "paging": {
    "offset": 0,
    "limit": 20,
    "results": 2,
    "total": 2
  },
  "sort": {
    "sortBy": "email",
    "sortDir": "asc"
  },
  "data": [
    {
      "id": 7,
      "email": "prueba@hotmail.com"
    },
    {
      "id": 6,
      "email": "prueba@prueba.com"
    }
  ]
}


### Crear nuevo contacto [POST]

## Elemento [/{account}/contacts/{id}]

### Obtener contacto [GET]

### Modificar contacto [PUT]

### Eliminar contacto [DELETE]



# Group Campañas

## Campaigns List [/{account}/campaigns{?q,offset,limit,sortby,sortdir}]

### Listar todas las campañas [GET]

+ Parameters
  + account: testaccount (string, required) - Nombre de la cuenta
  + offset: 0 (number, optional) - Inicio de paginado
  + limit: 10 (number, optional) - Cantidad de resultados
  + q (optional) - Búsqueda por `name`
  + sortby: name (enum[string], optional) - Tipo de ordenamiento
        + Members
            + `name`
            + `created`
            + `lastMailed`
  + sortdir: asc (enum[string], optional) - Sentido de ordenamiento
        + Members
            + `asc`
            + `desc`

+ Response 200 (application/json)

        {
            "url": "/testaccount/campaigns",
            "success" : true,
            "sort": {
                "sortby": "name",
                "sortdir": "asc"
            },
            "paging": {
                "offset": 0,
                "limit": 10,
                "results": 2,
                "total": 2
            },
            "data": [
                {
                    "id": 1,
                    "name": "Suscriptos a Newsletter",
                    "description": "Listado de contactos suscriptos al news",
                    "created": "2014-05-17 05:30:00+0000",
                    "lastMailed": "2014-05-18 05:30:00+0000",
                    "activeContacts": 120,
                    "totalContacts": 100,
                    "quality": 0.23,
                    "tags": [ ]
                }
            ]
        }

### Crear una nueva Campaña [POST]

+ Parameters
    + name: (string, required) - Nombre de la campaña
    + type (optional) - Tipo de campaña (default SIMPLE)
    + description (optional) - Descripcion de campaña
    + launchMode (enum[string], optional) - 

            + Default: `NOW`

            + Members
                + `NOW` - Enviar Campaña Ahora.
                + `SCHEDULED` - Enviar Campaña Programada.
    + launch (optional) - Fecha de envio . para especificar un fecha de launch, launchMode debe ser SCHEDULED
    + tags (optional) - Tags de campaña
    + options (optional) - Opciones de la campaña.
    + include (optional) - Include de la campaña.
    + exclude (optional) - Exlude de la campaña.

+ Response 200 (application/json)

        {
  "href": "/v2/testaccount/campaigns",
  "success": true,
  "data": {
    "id": 595,
    "name": "tests campaign",
    "description": "",
    "tags": [],
    "type": "SIMPLE",
    "state": "DRAFT",
    "launchMode": "NOW",
    "launchDate": null,
    "archived": null,
    "created": "2017-01-30T16:41:27Z",
    "lastModified": "2017-01-30T16:41:27Z",
    "recipients": null,
    "thumbnail": null,
    "metrics": null,
    "options": {
      "SHARE_FACEBOOK": "1",
      "GA_CAMPAIGN_NAME": "tests campaign",
      "GOOGLE_ANALYTICS": "1",
      "SHARE_LINKEDIN": "1",
      "TRACK_LINKS": "1",
      "VIEW_ONLINE": "1",
      "SHARE_TWITTER": "1",
      "SHARE_FORWARD": "1"
    },
    "include": {
      "lists": [],
      "interests": [],
      "campaigns": []
    },
    "exclude": {
      "lists": [],
      "interests": [],
      "campaigns": []
    },
    "contents": []
  }
}